name: My First Action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get my code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with: 
          node-version: 24

      - name: Check Node version
        run: node -v

